"""Константы, используемые в приложении quiz."""

MAX_CATEGORY_TITLE_LENGTH = 100
MAX_QUIZ_TITLE_LENGTH = 200
MAX_QUIZ_DESCRIPTION_LENGTH = 500
MAX_QUESTION_TEXT_LENGTH = 500
MAX_QUESTION_DESCRIPTION_LENGTH = 500
MAX_QUESTION_EXPLANATION_LENGTH = 250
MAX_STR_RETURN_LENGTH = 100
